[[redirects]]
  from = "/portfolio"
  to = "https://pixelpenportfolio.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio/*"
  to = "https://pixelpenportfolio.netlify.app/:splat"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"