[[redirects]]
  from = "/portfolio"
  to = "https://pixelpenportfolio.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio/*"
  to = "https://pixelpenportfolio.netlify.app/:splat"
  status = 200
  force = true